### ISSUE TITLE
Adding classical control

### ISSUE THREAD

**Issue by willzeng** [perak/quantum-circuit#1]
Any chance of adding classical control to circuits in the editor? This is often a great way of comparing QASM and Quil and takes some of the most effort to convert.

**Comment by perak** [comment]
@willzeng it is coming soon:

currently you can add only condition (QASM’s “if” translates to QUIL’s “jump”).

Other control constructs will be added soon - QUIL parser is next thing to be added to “quantum-circuit”.

**Comment by perak** [comment]
Later today I will publish video with instructions how to add classical control (condition) to circuit in GUI.

By the way, I found a bug related to exporting conditions to pyQuil and QUIL, will fix that and deploy fixed version of the GUI.

**Comment by perak** [comment]
@willzeng

OK, I fixed some bugs and published latest "quantum-circuit" npm module and latest "Quantum Programming Studio".

- Here is video showing how to add classical control (`if` in QASM) via Quantum Programming Studio GUI: https://youtu.be/4SfnwMr2aWg

P.S. in the video you can see that I am simulating using Rigetti QCS (running on QVM inside QMI), but that feature is not available yet (`qps-client` which connects QMI to "Quantum Programming Studio") is not published yet.

**Comment by willzeng** [comment]
That's great! I was able to finish the teleportation example: https://quantum-circuit.com/app_details/about/YpHEBY4QEJyB5G5i5

**Comment by perak** [comment]
@willzeng OK, but it doesn't work correctly due to bug: https://github.com/perak/quantum-circuit/issues/5 

currently, it teleports only "binary" values - qubit 2 will have resulting value of 0 or 1 whatever is "message" on qubit 0.

Bug is fixed now but not deployed yet. I will deploy in 1-2 hours.

**Comment by perak** [comment]
@willzeng fixed and deployed - works perfectly. I will close this issue now.
