### ISSUE TITLE
Get unitary matrix of the circuit

### ISSUE THREAD

**Issue by 6uliver** [perak/quantum-circuit#12]
It would be great if QuantumCircuit had a method to query the unitary matrix of the whole circuit.

After it will be implemented this matrix could be shown on the Quantum Programming Studio simulation page.

**Comment by perak** [comment]
Done :)

<img width="751" alt="Screen Shot 2019-10-19 at 1 15 55 AM" src="https://user-images.githubusercontent.com/5630814/67133651-1a868c00-f20e-11e9-8dec-edb5609d35b8.png">
