### ISSUE TITLE
problem with u2 gate

### ISSUE THREAD

**Issue by whu-dft** [perak/quantum-circuit#13]
OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
creg c[1];
h q[0];
u2 (0, 0) q[0];
u2 (0, 0) q[0];
u2 (0, 0) q[0];
u2 (0, 0) q[0];
u2 (0, 0) q[0];
measure q[0] -> c[0];

Please note that above circuit gives the result 16 by using quantum circuit, which is obviously wrong.

**Comment by perak** [comment]
@whu-dft thank you for reporting!

**Comment by perak** [comment]
@whu-dft fixed.

**Comment by whu-dft** [comment]
:ok_hand:  :smile:
