### ISSUE TITLE
Variables are not defined before use

### ISSUE THREAD

**Issue by tat757** [perak/quantum-circuit#14]
```qWireY```, ```qGateY```, ```cWireY``` in ```QuantumCircuit``` class are never defined before use. This is causing error when building the package.

They could be fixed by adding ```var``` before ```qWireY```, ```qGateY```, ```cWireY``` at line 7445, line 7449, line 7453 in ```/dist/quantum-circuit.js``` file

**Comment by perak** [comment]
@tat757 this is fixed now.

Thank you for reporting!
