### ISSUE TITLE
problem with cu3  gate

### ISSUE THREAD

**Issue by XIECHO** [perak/quantum-circuit#26]
![image](https://user-images.githubusercontent.com/22365301/61431158-22106d80-a95f-11e9-886d-63d433f9e6ee.png)

and i have a problem when we will use yy gate and ms gate.

**Comment by perak** [comment]
Hi @XIECHO thanks for reporting, it will be fixed asap. (You can help/speedup by reporting more details.)

**Comment by XIECHO** [comment]
![image](https://user-images.githubusercontent.com/22365301/61432521-584fec00-a963-11e9-95be-183141aa228e.png)
 
i think  the parameter is not right . aha

**Comment by XIECHO** [comment]
![image](https://user-images.githubusercontent.com/22365301/61432618-8e8d6b80-a963-11e9-8150-956426517f47.png)

the cu3 matrix

**Comment by perak** [comment]
@XIECHO What issues you have with YY gate? It looks good to me.

**Comment by XIECHO** [comment]
yy is good. i just want to know yy means , and when we will use yy gate. 
I am sorry that makes you confused.
发自我的iPhone

------------------ Original ------------------

**Comment by perak** [comment]
@XIECHO OK, published. Please update quantum-circuit package to version `0.9.94`.

`XX`, `YY` and `ZZ` gates are implemented natively in trapped-ion quantum computers. It is added by user request - I am not using it as well :)
