### ISSUE TITLE
 CNOT Gate is Not in Menu

### ISSUE THREAD

**Issue by iotexecutive** [perak/quantum-circuit#27]
Why is my CNOT Gate not displayed in the drag and drop menu?
Everything else seems to be fine.
Thanks

**Comment by perak** [comment]
Put “X” gate to one wire and then put “dot” to another wire (below or above “X” gate) and you’ll get CNOT gate. See video in docs section (it is under construction, but there is video)

**Comment by iotexecutive** [comment]
![X Gate](https://user-images.githubusercontent.com/20289190/61486731-c26b8f80-a969-11e9-8db5-40eb3062772d.JPG)

Thanks Perak,
I was following the video and as you can see from my picture, I have no X gate (NOT) to drag.
Best, Michael

**Comment by perak** [comment]
“X” gate is next to “ID” gate.

**Comment by perak** [comment]
Between ID and Y gates

**Comment by iotexecutive** [comment]
Oh Sorry Perak !
I was looking for the old circular symbol in the drag and drop menu.
Thank You.

**Comment by perak** [comment]
No problem! :) BTW, I changed it to “X” because users complained that they cannot find NOT gate, now I have opposite - users cannot find CNOT gate. Do you have idea how to make it obvius for both? (Maybe to add both X and circled X (bulb) symbols?
