### ISSUE TITLE
antlr source code?

### ISSUE THREAD

**Issue by wh5a** [perak/quantum-circuit#29]
Is QASM.g4 and other source files used to generate quantum-circuit.js available to public?

**Comment by perak** [comment]
Hi @wh5a 

- Here you can find QASM.g4 grammar: https://www.phoiyb.online/libtangle/QASM-Grammar/

- No other files - parser is generated from that grammar and is included into quantum-circuit source code (parser code is super ugly - I know, but works :) ).

**Comment by wh5a** [comment]
@perak Thanks for the explanation. Is the GUI of Quantum Programming Studio open sourced too? Especially the Drag & Drop feature?

**Comment by perak** [comment]
@wh5a GUI is not open sourced.
